### ISSUE TITLE
how to install on ARM?

### ISSUE THREAD

**Issue by benapetr** [TejasQ/gen-subs#17]
using npx gen-subs doesn't work on ARM:

```
Need to install the following packages:
  gen-subs@1.1.0
Ok to proceed? (y) y
/home/petrbena/.npm/_npx/9db3bb98a74ee7bb/node_modules/ffi-napi/lib/dynamic_library.js:75
    throw new Error('Dynamic Linking Error: ' + err);
          ^

Error: Dynamic Linking Error: /home/petrbena/.npm/_npx/9db3bb98a74ee7bb/node_modules/vosk/lib/linux-x86_64/libvosk.so: cannot open shared object file: No such file or directory
    at new DynamicLibrary (/home/petrbena/.npm/_npx/9db3bb98a74ee7bb/node_modules/ffi-napi/lib/dynamic_library.js:75:11)
    at Object.Library (/home/petrbena/.npm/_npx/9db3bb98a74ee7bb/node_modules/ffi-napi/lib/library.js:47:10)
    at Object.<anonymous> (/home/petrbena/.npm/_npx/9db3bb98a74ee7bb/node_modules/vosk/index.js:84:21)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:202:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)

Node.js v18.19.0
```

Seems like these packages aren't available for this architecture, is there a way to just compile this myself? Is there any build instruction?

**Comment by benapetr** [comment]
note that /home/petrbena/.npm/_npx/9db3bb98a74ee7bb/node_modules/vosk/lib/linux-x86_64/libvosk.so which was downloaded by npx is obviously x86_64, not aarch64 which I am on
